wandb_version: 1

C:
  desc: null
  value: 1
KMeans Cluster Count:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    code_path: code/main.py
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1657834959
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      4: 3.9.12
      5: 0.12.21
      8:
      - 5
    visualize:
      GK bars:
        panel_config:
          fieldSettings:
            label: gk_name
            value: correct_cluster
          panelDefId: wandb/bar/v0
          stringSettings:
            title: GK Optimal Cluster
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: GK bars_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      KMeans 1v1 Size:
        panel_config:
          fieldSettings:
            label: cluster
            value: count
          panelDefId: wandb/bar/v0
          stringSettings:
            title: Cluster Size in KMeans 1v1
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: KMeans 1v1 Size_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Spearman Correlation:
        panel_config:
          fieldSettings:
            x: rho
            y: pval
          panelDefId: wandb/scatter/v0
          stringSettings:
            title: null
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Spearman Correlation_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      TSNE 1v1:
        panel_config:
          fieldSettings:
            x: t-SNE_1
            y: t-SNE_2
          panelDefId: wandb/scatter/v0
          stringSettings:
            title: null
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: TSNE 1v1_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      TSNE Penalty:
        panel_config:
          fieldSettings:
            x: t-SNE_1
            y: t-SNE_2
          panelDefId: wandb/scatter/v0
          stringSettings:
            title: null
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: TSNE Penalty_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
    viz:
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
      elbow_curve:
        historyFieldSettings:
          key: elbow_curve
          x-axis: _step
        id: wandb/elbow/v1
      silhouette_plot:
        historyFieldSettings:
          key: silhouette_plot
          x-axis: _step
        id: wandb/silhouette_/v1
debug:
  desc: null
  value: false
grid_search:
  desc: null
  value: 1
hand:
  desc: null
  value: 1
height:
  desc: null
  value: 0
kernel:
  desc: null
  value: rbf
number_dimensions:
  desc: null
  value: 2
penalty_location:
  desc: null
  value: 0
save:
  desc: null
  value: 0
show:
  desc: null
  value: 0
split_sides:
  desc: null
  value: 0
view_invariant1:
  desc: null
  value: 1
view_invariant2:
  desc: null
  value: 1
