wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    code_path: code/main.py
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1657820469
    t:
      1:
      - 5
      - 53
      - 55
      4: 3.9.12
      5: 0.12.21
      8:
      - 5
